# UTS-1 All About Me

## Memahami Manusia

Tidak ada dari kita yang lahir mengetahui semuanya. Bahkan, kita masuk ke dunia ini tanpa mengetahui apa-apa. Kita bertahan hidup hanya melalui naluri dasar yang mendorong kita untuk melakukan aksi tertentu. Aksi tersebut pun hanya dapat meminta bantuan dari manusia-manusia lain di sekitar kita. Pada awalnya, semua manusia lahir tidak berdaya.

Namun, manusia adalah mahkluk yang terus belajar. Sejak awal kita lahir, kita selalu mengobservasi dunia di sekitar kita. Kita mempelajari bagaimana dunia itu bekerja. Kita juga coba berinteraksi dengan dunia dan melihat bagaimana responnya. Dari yang kita amati kita dapatkan pengetahuan dan dari yang kita lakukan kita dapatkan pengalaman.

Dalam mengeksplorasi dunia ini, kita menemukan bahwa dunia yang kita alami berbeda antara satu orang dengan orang lain. Kita semua hidup dalam dunia yang sama, tetapi dunia itu menunjukkan muka yang berbeda pada masing-masing individu. Dengan demikian kita belajar hal-hal berbeda, membangun pengetahun dan pengalaman masing-masing, dan menjadi pribadi-pribadi yang unik. Tanpa menjalani keseluruhan hidup orang lain, tidak mungkin kita memahami orang tersebut.

## Memahami Kesalahan

Dalam dunia ini, seringkali kita dengar kabar mengenai kesalahan yang dilakukan oleh orang-orang. Terkadang, kita sendiri merasakan langsung dampak dari kesalahan yang dilakukan oleh orang lain. Kesalahan ini dapat menyakiti kita, bahkan hingga mendalam. Karena demikian, kita dapat menanggap bahwa orang-orang tersebut merupakan orang yang buruk dan memang berusaha untuk menyakiti kita.

Walaupun demikian, tidak ada orang di dunia ini yang secara aktif berusaha menjadi pribadi yang buruk. Pribadi manusia tidak bisa dilepaskan dari keadaan lingkungannya. Setiap orang berusaha melakukan yang terbaik dengan semua informasi dan pengalaman yang dimilikinya. Sayang saja, pilihan yang dibuat berdasarkan informasi dan pengalaman yang diperoleh dalam suatu lingkungan belum tentu tepat dalam lingkungan yang lain. Hal tersebut menggambarkan salah satu kejahatan utama dunia ini. Manusia dipaksa membuat pilihan berdasarkan pengetahuan yang tidak lengkap dan pilihan ini melekat menjadi pribadi barunya.

## Memahami Diri Sendiri

Pada dua subbab sebelumnya, saya sudah menggambarkan pandangan saya terhadap dunia ini, khususnya pada sifat manusia. Namun, pandangan tersebut hanya bagian kecil dari apa yang membuat diri saya. Agar dapat mengenal saya dengan lebih lengkap, kita harus membahas detail-detail yang lebih di permukaan dan mungkin kurang menarik mengenai saya. Untuk menjelaskan hal tersebut, biarkan saya menggunakan nada yang lebih kasual.

Halo, aku Arlow Emmanuel Hergara, orang yang biasa-biasa saja. Aku adalah mahasiswa S1 Teknik Informatika di STEI ITB. Hobi-hobiku adalah main game, makan, dan tidur. Selain dari hobi, aku juga memiliki minat di bidang game development, software development, dan low level programming. Aku juga memiliki kepribadian yang cukup unik (menurut saya) dibandingkan dengan orang lain.

Aku adalah angkatan 2023 dari jurusan S1 Teknik Informatika di STEI ITB. Saya masuk karena ketertarikan saya dengan programming. Dari sejak kecil saya dipaparkan pada programming oleh ayahku dan hingga sekarang aku masih tertarik pada hal-hal yang bisa saya buat. Namun jika aku perlu jujur, aku merasa ketertarikan tersebut sudah tidak sekuat dulu semenjak masuk ITB. Sepertinya tugas tidak berakhir yang aku kerjakan setiap hari membuatku agak malas. Namun, aku tetap ingin semangat belajar mengenai programming apapun _challenge_-nya.

Hobi-hobiku (main game, makan, dan tidur) memang merupakan hobi yang dimiliki banyak orang lain. Ketiga hal itu sering saya lakukan untuk menghilangkan stres dari kesulitan sehari-hari (terkadang dilakuin terlalu banyak sih). Jika harus spesifik, game yang aku banyak main adalah game gacha, khususnya Genshin Impact dan game rhythm khususnya osu! (ayo main bareng kalau ada yang main juga). Untuk makan, aku bisa makan apa aja dan untuk tidur ya tidur.

Minat pertama yang aku dapatkan adalah game development. Bahkan game development adalah hal yang membuat aku tertarik dengan programming. Aku menjadi tertarik juga dalam software development setelah berusaha untuk membuat program-program berhubungan dengan game development yang bukan game. Minat aku terhadap low level programming muncul terakhir ketika mencoba melakukan hal yang membutuhkannya. Dalam semua hal yang aku minati, aku tertarik dengan bagaimana aku dapat membuat suatu sistem bekerja seperti yang aku ingini.

Aku mengatakan bahwa kepribadianku unik tetapi aku tidak tahu seberapa benar pernyataan itu. aku cenderung introvert yang tidak dapat berinteraksi dengan siapa saja. Namun untuk orang yang aku kenal, aku lumayan sering bercanda dan ngobrol. Aku juga seringkali melakukan hal-hal yang tidak jelas yang orang lain dapat saja menganggap mengesalkan. Sebelumnya aku sering takut melakukan hal-hal seperti itu tapi seiringnya waktu aku belajar untuk tidak memikirkannya karena orang pada umumnya tidak memerhatikan begitu banyak. Aku dulu orang yang suka sedih, tetapi sekarang aku lagi berusaha menjadi seseorang yang lebih ceria.